### ISSUE TITLE
Error	X3703 'main': vs_2_0 does not support minimum-precision data

### ISSUE THREAD

**Issue by howardlo** [arminms/HoliMoli#18]
Hi, I tried to compile and run HoliMoli using VS2015 Enterprise Update 3 with what I believe are all up to date stuff for HoloLens development but got this in the Error List window.

Error   X3703 'main': vs_2_0 does not support minimum-precision data

When I clicked on the error, it points to this line (line 27) in the file SimpleLightingPixelShader.hlsl

min16float4 main(PixelShaderInput input) : SV_TARGET

**Comment by arminms** [comment]
For a quick fix, right-click on SimpleLightingPixelShader.hlsl in VS2015 and select Properties. Then in 'HLSL Compiler' change 'Shader Model' to 'Shader Model 5.0'. I'll fix it in the next commit.

**Comment by howardlo** [comment]
HI Armin, thanks for the response but still the same. Sorry, I don't know enough about this to be more helpful but let me know if you want me try something else.

![capture](https://cloud.githubusercontent.com/assets/9260138/19361845/3e629af8-9152-11e6-8ab6-ea4bca0512e0.PNG)
![capture2](https://cloud.githubusercontent.com/assets/9260138/19361872/5a7ebf14-9152-11e6-8009-e4625791ff32.PNG)

**Comment by arminms** [comment]
You can either set 'Shader Type' (item above the 'Shader Model') to 'Pixel Shader (/ps)' or 'git pull' to the latest version . Let me know if you still have a problem building HoliMoli.

**Comment by howardlo** [comment]
Hi Armin,

I’m travelling but will try it when I get back.

Thank you so much!

Howard
